kuser/kinit:  NO_AFS unused-but-set-variable
When NO_AFS is defined, 'ret' is set but unused resulting in a build
failure on macOS.

  error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable