lib/ipc: set but unused 'kr' variables
mach_complete_async() and mach_complete_sync() are void functions.
Nothing uses the 'kr' value after being set which results in

  error: variable 'kr' set but not used [-Werror,-Wunused-but-set-variable]

Remove the variables.